# Generated by Django 6.0.1 on 2026-02-03 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_place', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_start_session', models.CharField(choices=[('MOR', 'Morning'), ('EVE', 'Evening')], default='MOR', max_length=3)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('event_end_session', models.CharField(choices=[('MOR', 'Morning'), ('EVE', 'Evening')], default='EVE', max_length=3)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('FOLLOW', 'Follow'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
