# Generated by Django 6.0.1 on 2026-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('FOLLOW UP', 'Follow Up'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost')], default='NEW', max_length=10),
        ),
    ]
