# Generated by Django 6.0.1 on 2026-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('FOLLOW', 'Follow'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost')], default='NEW', max_length=10),
        ),
    ]
