# Generated by Django 6.0.1 on 2026-02-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='project_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
