# Generated by Django 6.0.1 on 2026-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(max_length=255)),
                ('admin_label', models.CharField(max_length=50)),
                ('forgot_text', models.CharField(max_length=100)),
                ('remember_me_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
